"""initial migration

Revision ID: 4a29caded83
Revises: None
Create Date: 2015-09-07 14:54:17.375639

"""

# revision identifiers, used by Alembic.
revision = '4a29caded83'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('descr', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'descr')
    ### end Alembic commands ###
